### ISSUE TITLE
YouTube Music Icon

### ISSUE THREAD

**Issue by AqilCont** [manucabral/YoutubeMusicRPC#1]
Can you please show the actual Icon for Youtube Music for the Rich Presence, and maybe have the App name + Version on hover like how PreMid does? More people would use it since the current icon isn't really very good looking and is not the best for showing off your YT Music songs.

Also, I would appreciate a new, updated release!

**Comment by AqilCont** [comment]
IMO, this icon looks kind of ugly + the current application code does not work properly.
![image](https://user-images.githubusercontent.com/32044067/215860473-0a44414a-b2c7-416b-be32-a174ec0a594d.png)

**Comment by manucabral** [comment]
Hi, It is a great idea. I'm working on a new update.

**Comment by manucabral** [comment]
New update released

Version: [0.3](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.3)
