### ISSUE TITLE
Program does not stop after closing Tab

### ISSUE THREAD

**Issue by Shuckes** [manucabral/YoutubeMusicRPC#11]
Hey! I have found a "bug" in the program. Currently when you close the Opera (idk on other browsers) youtube music tab but not the program, the program continues to show that the last played song is being played. But it should instead show nothing.

**Comment by manucabral** [comment]
Thank you for your report. We will try to resolve it as soon as possible.

**Comment by manucabral** [comment]
Fixed, wait for the next update.
