### ISSUE TITLE
<bug> The specified file cannot be found

### ISSUE THREAD

**Issue by sh0ou** [manucabral/YoutubeMusicRPC#12]
**Describe the bug**
error "The specified file cannot be found"

**To Reproduce**
1.use google chrome (either open/close)
2.open Discord and enable status message settings
3.run YoutubeMusicRPC v0.5.1

**Expected behavior**
The application should start normally.

**Screenshots**
![image](https://github.com/manucabral/YoutubeMusicRPC/assets/47475540/8ffd4c14-612b-4e69-93ea-442c4c85be48)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Pro 64bit 22H2

**Additional context**
[client.log](https://github.com/manucabral/YoutubeMusicRPC/files/11711527/client.log)

**Comment by manucabral** [comment]
Hi, do you have the OS in Japanese?
Thank you for your report.

**Comment by sh0ou** [comment]
@manucabral  Yes.

**Comment by manucabral** [comment]
I'm going to work on this bug, thank you for the info.

**Comment by manucabral** [comment]
@sh0ou
I haven't been able to identify the problem yet. Here's a temp solution, manually running the browser.

chrome.exe --remote-debugging-port=9222 --remote-allow-origins=*

![Animation](https://github.com/manucabral/YoutubeMusicRPC/assets/83357673/3abb9b8e-d750-4640-b15c-40ed3ade34ce)
