### ISSUE TITLE
Unsupported browser, sorry

### ISSUE THREAD

**Issue by BojayB** [manucabral/YoutubeMusicRPC#2]
I opened up google chrome for this specific reason and it still wont work. I've closed all firefox instances (checked task manager too), restarted discord and chrome multiple times and still get the same error

INFO | App: youtube music rpc v0.3
App: installed
Presence: initialized
App: syncing (it will pause here sometimes, but not every time) 
Presence: connected
ERROR | App: unsupported browser, sorry
INFO | App: running
ERROR | App: not connected

Press any key to continue...

**Comment by BojayB** [comment]
I need to change my default browser to Google Chrome in my computer settings to be able to use it, so that should grt worked on eventually. And now that its gotten past the point mentioned above, it says

WARNING | App: remote debugging is not enabled
INFO | App: Starting browser remote debugging
ERROR | App: [WinError 2] The system xannot find the fine specified

Press any key to continue...

**Comment by manucabral** [comment]
Thank you for your report.

Please check the [new release version](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.4) which has support for Microsoft Edge (default Windows browser).

If the problem persist please reopen the issue.
