### ISSUE TITLE
<bug> Song isn't updating whenever a new song plays

### ISSUE THREAD

**Issue by cocobean402** [manucabral/YoutubeMusicRPC#20]
The app runs fine until a new song starts, it doesn't change the song title and stays on the fist song i was playing when i started it

**Comment by KILLXRX** [comment]
weirdly enough the release file won't even start for me. it exits at the first syncing, however when I tested it from the source it worked just fine. it seems like the release code isn't the same as the one in the source code (judging by the downloading the icon from an alternative source which I didn't find it's code in the source file)

TLDR: I will release a version in my own repository, run it and see if it works for you. [Releases](https://github.com/KILLXRX/YoutubeMusicRPC/releases)

**Comment by KILLXRX** [comment]
@cocobean402 try downloading the release I made.

**Comment by manucabral** [comment]
> 
Fixed. I used your release because I made a mistake and uploaded a testing version build instead of the actual source code.

**Comment by KILLXRX** [comment]
wonderful. I just tested it and verified it working, thanks. I might add the force update feature tomorrow.

off-topic: if you got a discord account add me there so it's easier to communicate and contribute together. my username is **n_lly**

**Comment by manucabral** [comment]
Flawless man

**Comment by manucabral** [comment]
> 

@cocobean402 Please, try using the new version of the app (v0.5.5). You can download it [here](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.5.5).
