### ISSUE TITLE
<discussion> wrong source code

### ISSUE THREAD

**Issue by KILLXRX** [manucabral/YoutubeMusicRPC#21]
Hey Manu, it seems like you forgot to publish your version's source code to the repository, It also had the same issue from the previous merge we made (ex: songs not updating) I assume you didn't download the newest files off the repository, I will update my fork to the latest version of your repository. and you can add any changes you'd like, such as the alternative icon download link which I noticed when I tried to run it without the icon it said "downloading from another source" which wasn't anywhere in the code of your repository.

> please download my current fork and add your adjustments to it then release it as the current release is broken.

**Comment by manucabral** [comment]
Done.
