### ISSUE TITLE
<bug>  No connection could be made

### ISSUE THREAD

**Issue by cocobean402** [manucabral/YoutubeMusicRPC#26]
![image_2023-10-13_124840473](https://github.com/manucabral/YoutubeMusicRPC/assets/131947571/3363c913-8ac8-4197-baff-b3008181fa8c)

i have tried everything.

**Comment by manucabral** [comment]
Hi, could you please tell me which version of Opera you have and send me the client.log file, please.
Thank you.

**Comment by starklite1** [comment]
It same like me, but work fine while using version 0.5.1 
my opera GX version LVL 5 (core: 102.0.4880.117)
[client.log](https://github.com/manucabral/YoutubeMusicRPC/files/13246284/client.log)
