### ISSUE TITLE
<bug> small_image is missing

### ISSUE THREAD

**Issue by Mamgo1128** [manucabral/YoutubeMusicRPC#27]
![螢幕擷取畫面 2023-10-20 163623](https://github.com/manucabral/YoutubeMusicRPC/assets/124562166/3d5c014e-5e9f-40cc-8976-beb68218bee1)
small_image is missing

**Comment by manucabral** [comment]
Hi,
Can you please attach the file client.log? 
Thank you for reporting it!

**Comment by Mamgo1128** [comment]
[client.log](https://github.com/manucabral/YoutubeMusicRPC/files/13062384/client.log)

**Comment by manucabral** [comment]
> [client.log](https://github.com/manucabral/YoutubeMusicRPC/files/13062384/client.log)

 I've been investigating. Could you let me know if this happens with all songs or only with specific ones?
