### ISSUE TITLE
<bug> Cant open Chrome when using YT Music as "Extension"

### ISSUE THREAD

**Issue by Shuckes** [manucabral/YoutubeMusicRPC#30]
**Describe the bug**
When you have chrome as your standard browser and the "Youtube Music Extension" installed you need to close all Chrome Tabs (so far so normal) but when the YT Music Tab is opened i cannot open another normal Chrome to browse.

**To Reproduce**
1. Have Chrome as Default Browser
2. When on YT Music Website click on the icon left from the Favorite Star (Or Translator)
3. Close all Chrome Tabs
4. Start YTMRPC
5. After YT Music Tab is opened, try opening another "Normal" Chrome Tab -> Wont work.

**Expected behavior**
I Should be able to make a new Chrome Tab without any issues.

**Desktop:**
 - OS: Windows
 - Version: 11 Home 64bit

**Comment by manucabral** [comment]
Hi Shuckes, first, you need to completely close the Chrome browser.

1. Close all instances of Google Chrome.
2. Open the YoutubeMusicRPC application; this will open a Chrome instance.
3. Now, you can browse and open the Youtube Music extension.
