### ISSUE TITLE
<feat> Can I hide "Play on YouTube Music" and also download the app button ?

### ISSUE THREAD

**Issue by KhangRuoi** [manucabral/YoutubeMusicRPC#31]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by manucabral** [comment]
Hi, 
The only way to remove that is by cloning the source code, modifying it to remove those buttons, and then manually executing it.

**Comment by KhangRuoi** [comment]
> Hi, The only way to remove that is by cloning the source code, modifying it to remove those buttons, and then manually executing it.

Can you add options in the setting.json for the upcoming update? I want to make my RPC setup simpler. if possible. Thank you.

**Comment by manucabral** [comment]
> Can you add options in the setting.json for the upcoming update? I want to make my RPC setup simpler. if possible. Thank you.

Yes, will be considered.
