### ISSUE TITLE
Browser Data Reset...? 

### ISSUE THREAD

**Issue by leoisdead** [manucabral/YoutubeMusicRPC#33]
**Describe the bug**
well i opened it a few times cuz it kept saying to CLOSE browser when it's not open and then it just basiclly reset all broswer data when i did manage to get it working

**To Reproduce**
i dunno

**Expected behavior**
well shouldn't reset browser data...

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Enterprise 64bit 23H2

**Comment by manucabral** [comment]
Hi @leoisdead,
Could you please let me know which browser this happened on? It's quite unusual for this to occur, as the application doesn't interact beyond the browser tabs. I am at your service.
