### ISSUE TITLE
<feat> Removing the "open browser" step

### ISSUE THREAD

**Issue by wtolman** [manucabral/YoutubeMusicRPC#34]
Hello, just made an account for this message. Everything is working great for me on Chrome so far. I'm using Windows 10. As a non programmer it was a little intimidating getting it set up but I quickly realized it wasn't too bad.

There's one thing I'm curious about, that being the "starting browser" step. I use the Youtube Music app, which works great with YoutubeMusicRPC, but it means I don't really need to open the chrome app directly to get things working. I don't know how important that step is for the Presence to decipher my browser data. Assuming it's supposed to just make the process easier on the user, it does the opposite in my case and for anyone else who wants to listen from the app. If there was an option to disable that step, that'd be a small but much appreciated quality of life change.

I'm just starting to use YoutubeMusicRPC so in the future I'll just close the chrome instance once it's opened. Like I said it detects the Youtube Music app without a hitch, and it's really just one extra mouse click so it's not a big issue.

If this is a confusingly worded, I'm sorry I have little understanding of how this stuff works. Cheers :)

**Comment by manucabral** [comment]
Hi @wtolman,
Thank you very much for trusting and using the app. I am considering setting the default connection without having to open a browser tab, but I will only implement it in a new version once I ensure it is secure. I will keep you notified!
