### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CryptiCaine** [manucabral/YoutubeMusicRPC#41]
[client.log](https://github.com/user-attachments/files/15525749/client.log)
Hello! Here's my client log, sorry, I don't know what I'm doing wrong. I had all browser instances shut and had Discord open

**Comment by CryptiCaine** [comment]
I'm on Windows 11, and this is happening on my first time opening the app. 
ERROR | App: Command 'WMIC PROCESS WHERE "name='{process_name}'" GET ExecutablePath' returned non-zero exit status 2147749902

**Comment by manucabral** [comment]
Hi,
Try using the [v0.5.1](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.5.1) version. The latest version has several incompatibilities.
