### ISSUE TITLE
WinError 10061

### ISSUE THREAD

**Issue by Mou67** [manucabral/YoutubeMusicRPC#46]
**Describe the bug**
WARN | App: Please close all browser instances and try again. Also, close Youtube Music Desktop App if you are using it.

**To Reproduce**
just open the exe and it pops up

**Expected behavior**
That the RPC will work

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

![image](https://github.com/manucabral/YoutubeMusicRPC/assets/65969554/4fa7ec56-0f36-48a1-ae0a-35248dd03673)

**Comment by manucabral** [comment]
Hi,
Try using the [v0.5.1](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.5.1) version. The latest version has several incompatibilities. If you get the same error, please let me know.
Thanks for report it.
