### ISSUE TITLE
Whole PC lags when updating Presence

### ISSUE THREAD

**Issue by Shuckes** [manucabral/YoutubeMusicRPC#6]
When the Program sees that a new song is played and updates the Presence, my complete computer (also the song) lags around in 1 second intervals and i continues afterwards for around 1-2 minutes.

**Comment by Shuckes** [comment]
What i forgot to mention, it also continues to lag afterwards even when i closed the program.

**Comment by manucabral** [comment]
Thanks you for report it, can you give me the your pc properties?

**Comment by Shuckes** [comment]
Of Course.
Device name LittlePengluin
Processor 12th Gen Intel(R) Core(TM) i5-12400F 2.50 GHz
Installed RAM 16.0 GB (15.8 GB usable)
Geräte-ID F9D54BFB-CA67-4212-873F-8CDE2106EFB4
Produkt-ID 00325-96348-60868-AAOEM
System type 64-bit operating system, x64-based processor
Pen and touch input Pen or touch input is not available for this display.

**Comment by Shuckes** [comment]
Edition Windows 11 Home
Version 22H2
Installed on 04/13/2023
Operating system build 22621.1702
Performance Windows Feature Experience Pack 1000.22641.1000.0

**Comment by Shuckes** [comment]
Any news?

**Comment by manucabral** [comment]
A new version was released [0.4.2](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.4.2). There will be more updates about the perf, meanwhile don't close the issue please.

**Comment by Shuckes** [comment]
So i have tried it yesterday for around 3 hours while playing games and doing work. Currently i do not have any lags so the fix worked. My PC works completely normal now 👍

**Comment by Shuckes** [comment]
One other thing though. I tried it just now again and after the first song i played was done and the new one started it did not update after ~1 minute so the program stops updating. client.log attached.
[client.log](https://github.com/manucabral/YoutubeMusicRPC/files/11489771/client.log)

**Comment by manucabral** [comment]
I think it's a windows console problem, I'm still looking for an effective solution but for now to fix it you need to press enter in the console.

**Comment by Shuckes** [comment]
Also I´ve got a question. How do i use the Youtube Music Desktop App with your Program?

**Comment by manucabral** [comment]
> Unfortunately i dont know a thing about coding, i really want this application to work good. If you got any new Stuff to test. Im open for App-Testing.

Thank you so much, can you give me a way to reach you in case to do some testing? Maybe a contact of yours?

**Comment by manucabral** [comment]
> Also I´ve got a question. How do i use the Youtube Music Desktop App with your Program?

Of course, 
1. Close all instances of Microsoft Edge
2. Run the application
3. If the app has connected successfully, open Youtube Music Desktop App
![image](https://github.com/manucabral/YoutubeMusicRPC/assets/83357673/bbae2fdf-1003-49e1-82f9-d496b7564939)

![image](https://github.com/manucabral/YoutubeMusicRPC/assets/83357673/82eff26e-baf8-403d-8929-014088cde9de)

Result
![image](https://github.com/manucabral/YoutubeMusicRPC/assets/83357673/d472620a-b5ff-4604-9eb7-f1d60c843e0d)

**Comment by manucabral** [comment]
Something to keep in mind is that Microsoft Edge doesn't always fully close, so you may need to close it through the Task Manager at times before running the app (Youtube Music RPC)
