### ISSUE TITLE
Support for Opera One and the Youtube music Application

### ISSUE THREAD

**Issue by Nitlix** [manucabral/YoutubeMusicRPC#7]
The title is exactly what it says to be! By the youtube music application I mean, installing the Youtube music app from **chrome** and using it as a seperate window.

**Comment by manucabral** [comment]
Hi, support for Opera One will be added. Thanks for you request.

Alternatively, you can use the YouTube Music app (from chrome) by first opening YouTubeMusicRPC and then opening the application.

![image](https://github.com/manucabral/YoutubeMusicRPC/assets/83357673/85a950e5-101f-48fa-9dc1-6d89b0c58854)

**Comment by Shuckes** [comment]
Support for the whole Opera "Collection" would be great. So also Opera GX

**Comment by manucabral** [comment]
Support for Opera browsers (Normal, One and GX) has been added in the latest [release v0.5.0](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.5.0)

**Comment by Shuckes** [comment]
I do not have any problems with Opera GX. Only the "App: Same Tab." all the time.

**Comment by Nitlix** [comment]
> Hi, support for Opera One will be added. Thanks for you request.
> 
> Alternatively, you can use the YouTube Music app (from chrome) by first opening YouTube Music Rich Presence.exe and then opening the YouTube Music app.
> 
> ![image](https://user-images.githubusercontent.com/83357673/239711038-85a950e5-101f-48fa-9dc1-6d89b0c58854.png)


Hey, in both situations (opening the presence before the app, and after) it still can't detect the app...
<img width="1260" alt="image" src="https://github.com/manucabral/YoutubeMusicRPC/assets/66027553/cc0c29e4-bbfb-41ea-9d08-767611c8c5b1">

**Comment by Nitlix** [comment]
Accidentally closed it, apologies :)

**Comment by Nitlix** [comment]
Hey again, now it automatically detects that I have opera and tries to open a new window of the browser, and then throws this error: 

<img width="851" alt="image" src="https://github.com/manucabral/YoutubeMusicRPC/assets/66027553/bef88c0b-64df-4d9a-a20b-fc15e4ce86b7">

**Comment by ne0de** [comment]
> Hey again, now it automatically detects that I have opera and tries to open a new window of the browser, and then throws this error:
> 
> <img alt="image" width="851" src="https://user-images.githubusercontent.com/66027553/239990352-bef88c0b-64df-4d9a-a20b-fc15e4ce86b7.png">

The app opens the browser in listening mode (a new window) to request the songs you are listening to. That's why it prompts you to close any instances that were not opened by the application, as it may encounter a pre-existing browser window and refuse to work properly.

**Comment by ne0de** [comment]
I closed everything and it works correctly for me

**Comment by Nitlix** [comment]
Hey, yeah I did the same thing now and it actually worked xD

Many thanks
